### PR TITLE
Revamped UI

### PR DESCRIPTION
**Pull request by Hrily**
I've created a new UI for the game as required in #5. Hope you like it...

screenshot_20161021-123221
screenshot_20161021-123229
screenshot_20161021-123345
screenshot_20161021-123333
screenshot_20161021-123341
screenshot_20161021-123235

### CODE REVIEW

**Comment by jitendra3109** [comment]
@Hrily  Thanks for create a better Activity_Game and would also give a transparent color or maybe interactive and other activity also. After that i will merge your pull request.

**Comment by Hrily** [comment]
What color would you like...?

**Comment by jitendra3109** [comment]
Thanks for asking me but I don't know which color be better .If you are creative enough then I think you can do this.
Please change whole UI.
I can give some example
screenshot_2016-10-22-11-02-19
screenshot_2016-10-22-10-59-59
screenshot_2016-10-22-10-59-44
screenshot_2016-10-16-00-34-29
screenshot_2016-10-16-00-34-20
screenshot_2016-10-16-00-34-11

**Comment by Hrily** [comment]
I like this ABA ones, I can do it.
Do you have any image in mind?

**Comment by jitendra3109** [comment]
If you can check related to best image , that should be good.

**Comment by jitendra3109** [comment]
Hello @Hrily
Are you on work ?

**Comment by Hrily** [comment]
I've found these images, tell me whether you like it?

sat-subject-test-mathematics-level-1_119817_large
math
hundreds boards2
math-chalkboard

**Comment by jitendra3109** [comment]
last one will be okay but you need to go all UI page  and every activity to be fitted color.

**Comment by jitendra3109** [comment]
@Hrily  Please could send be your work pull request.

**Pull request merged**
